/**
 * Report Model
 *
 * Stores generated report metadata for history and re-download.
 * Uses TTL index to automatically delete expired reports after 7 days.
 */

const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema(
  {
    templateId: {
      type: String,
      required: [true, 'Template ID is required'],
    },
    templateName: {
      type: String,
      required: [true, 'Template name is required'],
    },
    category: {
      type: String,
      enum: ['operational', 'attendance', 'incidents', 'clients', 'compliance'],
      required: [true, 'Category is required'],
    },
    dateRange: {
      start: {
        type: Date,
        required: [true, 'Start date is required'],
      },
      end: {
        type: Date,
        required: [true, 'End date is required'],
      },
    },
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Generated by user is required'],
    },
    generatedByName: {
      type: String,
      required: [true, 'Generated by name is required'],
    },
    format: {
      type: String,
      enum: ['pdf', 'xlsx', 'csv'],
      default: 'pdf',
    },
    status: {
      type: String,
      enum: ['pending', 'ready', 'failed'],
      default: 'ready',
    },
    fileSize: {
      type: Number,
      default: 0,
    },
    expiresAt: {
      type: Date,
      default: () => new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
    },
  },
  {
    timestamps: true,
  }
);

// ============================================
// Virtual Properties
// ============================================

/**
 * Virtual for download URL
 */
reportSchema.virtual('downloadUrl').get(function () {
  return `/api/reports/download/${this._id}`;
});

// Ensure virtuals are included in JSON output
reportSchema.set('toJSON', { virtuals: true });
reportSchema.set('toObject', { virtuals: true });

// ============================================
// Indexes
// ============================================

// Index for queries by user and creation date
reportSchema.index({ generatedBy: 1, createdAt: -1 });

// Index for template statistics aggregation
reportSchema.index({ templateId: 1, createdAt: -1 });

// TTL index - automatically delete documents after expiresAt date
reportSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

// ============================================
// Export Model
// ============================================

module.exports = mongoose.model('Report', reportSchema);